from .auth.activateAccount import *
from .auth.changePassword import *
from .auth.changeProfile import *
from .auth.login import *
from .auth.logout import *
from .auth.signup import *
from .components.cart import *
from .components.change import *
from .components.add import *
from .components.delete import *
from .components.fieldEditUpdate import *
from .components.edit import *
from .pages.search import *
from .pages.admin import *
from .pages.home import *
from .pages.product import *
from .pages.cart import *
from .pages.enquiry import *
from .pages.order import *
from .pages.checkout import *
from .pages.categories import *
from .pages.brands import *
from .pages.allProducts import *
from .pages.featured import *
from .pages.profile import *